name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "Dhanush Rajashekar"
          git config --global user.email "dhanushrajashekar1315@gmail.com"

      - name: Generate Snake
        uses: Platane/snk@v2
        id: generate_snake
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Push Changes
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: output  # The branch to deploy to
          folder: dist    # The folder to deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
